services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
